name: Run Coverage on PR
on: pull_request

jobs:
  build-and-run-coverage:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Prisma
        run: cd apps/server && npm run prisma:generate

      - name: Build
        run: npm run build

      - name: Run client test and coverage
        run: npm run coverage

      - name: Report client coverage
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: ./apps/client

      - name: Report server coverage
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: ./apps/server/src
